name: CAD flow

on:
  workflow_dispatch:
    inputs:
      select_issues:
        description: 'Issue numbers to be deployed'
        required: true
        type: string

      review-env:
        description: Which cluster?
        required: true
        type: choice
        options:
          - cad-designer-a.flowniq.com
          - cad-designer-b.flowniq.com
          - cad-designer-c.flowniq.com
          
jobs:
  merge-compile:
    name: "Merge and compile the issues : ${{inputs.select_issues}}"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3      
      - name: Get review ID
        id: review-name
        run: |
          echo "Env choosen ${{ steps.review-name.outputs.review_id }}"
          echo "review_id=`echo ${{ inputs.review-env }} | sed -e 's/.*designer-\([a-z]*\).*/\1/g'`" >> $GITHUB_OUTPUT
      - name: Show the var
        run: |
          echo "Env choosen ${{ steps.review-name.outputs.review_id }}" 
      - name: "Merge all issues"
        run: |
          echo $GITHUB_JOB
          git checkoub -f cad-${{ env.GITHUB_JOB }}
      - name: "Show PRs"
        run: |
          env
          gh auth status
          gh pr ls
        
