name: CAD flow

on:
  workflow_dispatch:
    inputs:
      select_issues:
        description: 'Issue numbers to be deployed'
        required: true
        type: string

      review-env:
        description: Which cluster?
        required: true
        type: choice
        options:
          - cad-designer-a.flowniq.com
          - cad-designer-b.flowniq.com
          - cad-designer-c.flowniq.com
          
jobs:
  merge-compile:
    name: "Merge and compile the issues : ${{inputs.select_issues}}"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      MY_KEY: "${{ secrets.CCB_KEY }}"
    steps:
      - uses: actions/checkout@v3
      - name: Save the secret CCB_KEY in a file
        run: |
          echo "${MY_KEY}" >> secret.file
          echo "The content is protected in log-output...?"
          cat secret.file
        
      - name: Aument the env vars space
        run: |
          echo "ccb_var_hause=HAUPSTR" >> $GITHUB_ENV
      - name: Get review ID
        id: review-name
        run: |
          echo "Env choosen ${{ steps.review-name.outputs.review_id }}"
          echo "review_id=`echo ${{ inputs.review-env }} | sed -e 's/.*designer-\([a-z]*\).*/\1/g'`" >> $GITHUB_OUTPUT
          echo "And here is ${{ env.ccb_var_hause }} "
          ./example.sh
      - name: Show the var
        run: |
          echo "Env choosen ${{ steps.review-name.outputs.review_id }}" 
      - name: "Merge all issues"
        run: |
          set -x
          git fetch --unshallow origin
          git branch -a
          cad_branch="cad-$GITHUB_RUN_ID"
          git checkout -b ${cad_branch}
          branches=`git branch -a | grep issue-11`
          git config user.email "ccastill100@gmail.com"
          git config user.name "Cesar CI"
          git merge --log -m "CAD merge deploy for github ID $GITHUB_RUN_ID" $branches
          git push origin HEAD:$cad_branch
          gh pr create --title "Title for $cad_branch"  --body "Branches are:  $GITHUB_RUN_ID" -B main

      - name: "Show PRs"
        run: |
          env
          gh auth status
          gh pr ls
        
