name: CAD flow

on:
  workflow_dispatch:
    inputs:
      select_issues:
        description: 'Issue numbers selection'
        required: true
        type: string

      build-and-deploy:
        description: Which cluster?
        required: true
        type: choice
        options:
          - Cluster-A
          - Cluster-B
          - Cluster-C          
          
jobs:
  merge-compile:
    name: "Merge and compile the issues : ${{inputs.select_issues}}"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3      
      - name: "Fetch all the issue branches"
        id: fetch-branches
        run: |
          git branch -a
          cat .git/config
          git fetch origin
          git branch -a
          echo "issues ${{inputs.select_issues}}"
          ./cadflow/merge_compile.sh ${{inputs.select_issues}}
