name: CAD flow

on:
  workflow_dispatch:
    inputs:
      issues:
        description: 'Issue numbers selection'
        required: true
        type: string

      cluster:
        description: Which cluster?
        required: true
        type: choice
        options:
          - Cluster-A
          - Cluster-B
          - Cluster-C          
          
jobs:
  merge-compile:
    name: "Merge and compile the issues : ${{inputs.issues}}"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3      
      - name: "Fetch all the issue branches"
        id: fetch-branches
        run: |
          git branch -a
          cat .git/config
          git fetch origin
          git branch -a
          echo "issues ${{inputs.issues}}"
          ./cadflow/merge_compile.sh ${{inputs.issues}}
          
