name: Testing Vars
env:
  var_a: 'Value-A'

on:
  push:
    branches:
      - master
      - main

  workflow_call:
    inputs:
      extra:
        description: 'Extra'
        required: true
        type: string
        default: defaultExtra
jobs:
  job-1:
    name: "My first job with $var_a"
    runs-on: ubuntu-latest
    steps:
      - name: Get the tip
        id: get-tip
        run: echo "tip_m=`echo ${{ github.event.head_commit.message }} | grep 'be skip' || echo 'fallback_tip'`" >> $GITHUB_OUTPUT
      
      - run: |
          echo "Hi job-1: var_a = $var_a"
          echo "inputs.extra: ${{inputs.extra}}"

      - run: |
          echo "Latest message: ${{ steps.get-tip.outputs.tip_m }}"
