name: Testing Vars
env:
  var_a: 'Value-A'

on:
  push:
    branches:
      - master
      - main
jobs:
  job-1:
    name: My first job with $var_a
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hi job-1"
