name: Testing Vars
env:
  var_a: 'Value-A'

on:
  push:
    branches:
      - master
      - main

  workflow_call:
    inputs:
      extra:
        description: 'Extra'
        required: true
        type: string
        default: defaultExtra
jobs:
  generate-tip-message:
    runs-on: ubuntu-latest
    outputs:
      TIP_MESSAGE: ${{ github.event.head_commit.message }}
  
  job-1:
    name: "My first job with $var_a"
    needs: generate-tip-message
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hi job-1: var_a = $var_a"
          echo "inputs.extra: ${{inputs.extra}}"

      - run: |
          echo "Latest message: ${{ needs.generate-tip-message.ouputs.TIP_MESSAGE}}"
